services:
  - type: web
    name: harr
    runtime: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails db:migrate && bundle exec rails server -p $PORT
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false   # preencher manualmente no dashboard do Render
      - key: DATABASE_URL
        fromDatabase:
          name: harr-db
          property: connectionString
      - key: TMDB_API_KEY
        sync: false   # preencher manualmente no dashboard do Render
      - key: RAILS_LOG_LEVEL
        value: info

databases:
  - name: harr-db
    databaseName: harr_production
    user: harr
    postgresMajorVersion: 17
