# PostgreSQL
default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['HARR_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: harr_development

test:
  <<: *default
  database: harr_test

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
